'use client';

import { useState } from 'react';
import { Clock3, MapPin, Building2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';

export default function SettingsPage() {
  const [message, setMessage] = useState('');
  return <div className="space-y-5"><header><p className="text-[10px] font-extrabold uppercase tracking-[.15em] text-muted-foreground">Company configuration · local demo</p><h1 className="mt-1 text-3xl font-bold tracking-tight">Settings</h1><p className="mt-2 text-sm text-muted-foreground">Prepare the operating rules the backend will later validate. Provider credentials and secrets never appear here.</p></header>{message && <p className="rounded-md border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-950">{message}</p>}<div className="grid gap-4 xl:grid-cols-3"><Card><CardHeader><Building2 className="size-5 text-ops-success"/><CardTitle>Company profile</CardTitle></CardHeader><CardContent><form action={() => setMessage('Company profile saved in this local demo.')} className="space-y-3"><label className="grid gap-2 text-sm font-medium">Company name<Input defaultValue="Retell Construction"/></label><label className="grid gap-2 text-sm font-medium">Reply email<Input type="email" defaultValue="dispatch@example.com"/></label><Button className="w-full">Save profile</Button></form></CardContent></Card><Card><CardHeader><Clock3 className="size-5 text-ops-success"/><CardTitle>Business hours</CardTitle></CardHeader><CardContent><form action={() => setMessage('Business hours saved in this local demo.')} className="space-y-3"><label className="grid gap-2 text-sm font-medium">Weekdays<Input defaultValue="8:00 AM – 6:00 PM"/></label><label className="grid gap-2 text-sm font-medium">Weekends<Input defaultValue="Closed"/></label><Button className="w-full">Save hours</Button></form></CardContent></Card><Card><CardHeader><MapPin className="size-5 text-ops-success"/><CardTitle>Service areas</CardTitle></CardHeader><CardContent><form action={() => setMessage('Service areas saved in this local demo.')} className="space-y-3"><label className="grid gap-2 text-sm font-medium">Primary coverage<Input defaultValue="Austin, Round Rock, Pflugerville, Leander"/></label><p className="text-xs leading-5 text-muted-foreground">The backend must validate a caller’s address before any appointment is confirmed.</p><Button className="w-full">Save areas</Button></form></CardContent></Card></div><Card className="border-amber-300 bg-amber-50"><CardContent className="p-4 text-sm leading-6 text-amber-950"><b>Integration status:</b> Retell, notifications, storage, and databases are intentionally not connected in this frontend-only stage.</CardContent></Card></div>;
}
