'use client';

import Link from 'next/link';
import { useState } from 'react';
import { Plus, Search } from 'lucide-react';
import { useBookings } from '@/components/admin/booking-store';
import { bookingStatus, formatBookingSchedule } from '@/lib/booking-utils';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';

export default function BookingsPage() {
  const { bookings, technicianName, status, error, retry } = useBookings();
  const [query, setQuery] = useState('');
  const visible = bookings.filter((booking) => `${booking.customer} ${booking.service} ${technicianName(booking.technicianId)}`.toLowerCase().includes(query.toLowerCase()));
  if (status === 'loading') return <Card><CardContent className="py-14 text-center"><h1 className="text-xl font-bold">Loading bookings…</h1><p className="mt-2 text-sm text-muted-foreground">Preparing the scheduling workspace.</p></CardContent></Card>;
  if (status === 'error') return <Card><CardContent className="py-14 text-center"><h1 className="text-xl font-bold">Bookings could not load</h1><p className="mt-2 text-sm text-muted-foreground">{error}</p><Button className="mt-5" onClick={() => void retry()}>Try again</Button></CardContent></Card>;
  return <div className="space-y-5"><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[10px] font-extrabold uppercase tracking-[.15em] text-muted-foreground">Manual scheduling · {bookings.length} upcoming</p><h1 className="mt-1 text-3xl font-bold tracking-tight">Bookings</h1></div><Button asChild><Link href="/bookings/new"><Plus/>New booking</Link></Button></header><Card className="border-amber-300 bg-amber-50 py-0"><CardContent className="p-4 text-sm text-amber-950"><b>Manual assignment only.</b> The admin reviews every booking, chooses a technician, then shares the customer details directly.</CardContent></Card><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div className="relative w-full sm:max-w-sm"><Search className="absolute top-1/2 left-3 size-4 -translate-y-1/2 text-muted-foreground"/><Input id="booking-search" value={query} onChange={(event) => setQuery(event.target.value)} className="pl-9" placeholder="Search customer, service, or technician"/></div><span className="text-sm text-muted-foreground">{visible.length} result{visible.length === 1 ? '' : 's'}</span></div><Card className="py-0"><Table><TableHeader><TableRow><TableHead>Customer</TableHead><TableHead>Service & address</TableHead><TableHead className="hidden lg:table-cell">Booking time</TableHead><TableHead className="hidden xl:table-cell">Technician</TableHead><TableHead>Status</TableHead><TableHead className="text-right">Action</TableHead></TableRow></TableHeader><TableBody>{visible.map((booking) => { const pending = booking.status === 'Pending review' || booking.status === 'Needs verification'; return <TableRow key={booking.id}><TableCell><p className="font-semibold">{booking.customer}</p><p className="mt-1 text-xs text-muted-foreground">{booking.phone}</p></TableCell><TableCell><p className="font-semibold">{booking.service}</p><p className="mt-1 max-w-48 truncate text-xs text-muted-foreground">{booking.address}</p></TableCell><TableCell className="hidden lg:table-cell">{formatBookingSchedule(booking)}</TableCell><TableCell className="hidden xl:table-cell">{technicianName(booking.technicianId) || <span className="text-muted-foreground">Not assigned</span>}</TableCell><TableCell><Badge variant={pending ? 'secondary' : booking.status === 'Cancelled' ? 'destructive' : 'default'}>{bookingStatus(booking)}</Badge></TableCell><TableCell className="text-right"><Button asChild variant="ghost" size="sm"><Link href={`/bookings/${booking.id}`}>Review</Link></Button></TableCell></TableRow>; })}</TableBody></Table>{visible.length === 0 && <CardContent className="py-12 text-center text-sm text-muted-foreground">No bookings match this search. Try another customer, service, or technician name.</CardContent>}</Card></div>;
}
