import { CallVolumeChart } from '@/components/admin/call-volume-chart';
import { Badge } from '@/components/ui/badge';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { operationsRepository } from '@/lib/operations-repository';

export default function AnalyticsPage() {
  const calls = operationsRepository.listCalls();
  const leads = operationsRepository.listLeads();
  const bookingsCreated = calls.filter((call) => call.outcome === 'Booking created').length;
  const qualifiedLeads = leads.filter((lead) => lead.status === 'Qualified').length;
  const chartValues = [0, 0, 0, 0, 0, 0, calls.length];
  const metrics = [{ label: 'Calls reviewed', value: calls.length, definition: 'Inbound calls in the current local fixture.' }, { label: 'Booking conversion', value: `${bookingsCreated}/${calls.length}`, definition: 'Calls whose recorded outcome created a booking.' }, { label: 'Qualified leads', value: qualifiedLeads, definition: 'Lead records currently marked qualified.' }];
  return <div className="space-y-5"><header><p className="text-[10px] font-extrabold uppercase tracking-[.15em] text-muted-foreground">Measurement definitions · local demo</p><h1 className="mt-1 text-3xl font-bold tracking-tight">Analytics</h1><p className="mt-2 text-sm text-muted-foreground">These metrics are calculated from the local fixture. Backend events will replace this data after integration.</p></header><section className="grid gap-4 md:grid-cols-3">{metrics.map((metric) => <Card key={metric.label}><CardHeader><p className="text-xs font-semibold text-muted-foreground">{metric.label}</p><CardTitle className="text-3xl">{metric.value}</CardTitle></CardHeader><CardContent className="text-sm leading-6 text-muted-foreground">{metric.definition}</CardContent></Card>)}</section><section className="grid gap-4 xl:grid-cols-[1.25fr_.75fr]"><Card><CardHeader><p className="text-[10px] font-extrabold uppercase tracking-[.13em] text-muted-foreground">Volume</p><CardTitle>Inbound calls</CardTitle></CardHeader><CardContent><CallVolumeChart values={chartValues}/><p className="mt-3 text-xs text-muted-foreground">The chart represents local fixture volume only; it is not a production report.</p></CardContent></Card><Card><CardHeader><p className="text-[10px] font-extrabold uppercase tracking-[.13em] text-muted-foreground">Definitions</p><CardTitle>How to read this view</CardTitle></CardHeader><CardContent className="space-y-3 text-sm text-muted-foreground"><p><b className="text-foreground">Booking conversion</b> counts the explicit call outcome, not an inferred sale.</p><p><b className="text-foreground">Qualified leads</b> require an admin decision.</p><p><b className="text-foreground">No production claim</b> is made while this app uses mock data.</p></CardContent></Card></section><Card className="overflow-hidden py-0"><Table><TableHeader><TableRow><TableHead>Outcome</TableHead><TableHead>Calls</TableHead><TableHead>Definition</TableHead></TableRow></TableHeader><TableBody>{(['Booking created', 'Lead created', 'Resolved', 'Failed'] as const).map((outcome) => { const count = calls.filter((call) => call.outcome === outcome).length; return <TableRow key={outcome}><TableCell><Badge variant={outcome === 'Failed' ? 'destructive' : outcome === 'Booking created' ? 'default' : 'secondary'}>{outcome}</Badge></TableCell><TableCell>{count}</TableCell><TableCell className="text-muted-foreground">Calls recorded with this outcome in the local fixture.</TableCell></TableRow>; })}</TableBody></Table></Card></div>;
}
