import Link from 'next/link';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { operationsRepository } from '@/lib/operations-repository';

export default async function CallDetailPage({ params }: { params: Promise<{ callId: string }> }) {
  const call = operationsRepository.getCall((await params).callId);
  if (!call) return <Card><CardContent className="py-14 text-center"><h1 className="text-xl font-bold">Call not found</h1><p className="mt-2 text-sm text-muted-foreground">This call is not available in the local fixture.</p><Button asChild className="mt-5"><Link href="/calls">Back to calls</Link></Button></CardContent></Card>;
  const lead = operationsRepository.listLeads().find((item) => item.sourceCallId === call.id);
  const followUp = call.outcome === 'Lead created' ? { href: lead ? `/leads/${lead.id}` : '/leads', label: 'Review lead' } : call.outcome === 'Booking created' ? { href: '/bookings', label: 'Review booking' } : null;
  return <div className="space-y-5"><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[10px] font-extrabold uppercase tracking-[.15em] text-muted-foreground">Call review · {call.id}</p><h1 className="mt-1 text-3xl font-bold tracking-tight">{call.customer}</h1><p className="mt-2 text-sm text-muted-foreground">{call.startedAt} · {call.duration} · {call.phone}</p></div><Button asChild variant="outline"><Link href="/calls">← Back to calls</Link></Button></header><section className="grid gap-4 xl:grid-cols-[1.25fr_.75fr]"><Card><CardHeader className="flex-row items-start justify-between gap-3"><div><p className="text-[10px] font-extrabold uppercase tracking-[.13em] text-muted-foreground">Conversation</p><CardTitle className="mt-1">{call.service}</CardTitle></div><Badge variant={call.outcome === 'Booking created' ? 'default' : call.outcome === 'Failed' ? 'destructive' : 'secondary'}>{call.outcome}</Badge></CardHeader><CardContent className="space-y-3">{call.transcript.map((line, index) => <div key={`${line.speaker}-${index}`} className={`rounded-lg border p-3 ${line.speaker === 'Retell' ? 'ml-5 bg-muted/60' : 'mr-5 bg-background'}`}><p className="text-[10px] font-extrabold uppercase tracking-[.12em] text-muted-foreground">{line.speaker}</p><p className="mt-1 text-sm leading-6">{line.text}</p></div>)}</CardContent></Card><div className="space-y-4"><Card><CardHeader><p className="text-[10px] font-extrabold uppercase tracking-[.13em] text-muted-foreground">AI summary</p><CardTitle>Review before action</CardTitle></CardHeader><CardContent className="space-y-4"><p className="text-sm leading-6 text-muted-foreground">{call.summary}</p><dl className="grid gap-3 text-sm"><div className="flex justify-between gap-4"><dt className="text-muted-foreground">Verification</dt><dd className="font-medium">{call.verification}</dd></div><div className="flex justify-between gap-4"><dt className="text-muted-foreground">Recording</dt><dd className="font-medium">Unavailable in demo</dd></div></dl>{followUp ? <Button asChild className="w-full"><Link href={followUp.href}>{followUp.label}</Link></Button> : <p className="rounded-md bg-amber-50 p-3 text-xs text-amber-950">No automatic follow-up is available. Review this result manually.</p>}</CardContent></Card></div></section></div>;
}
