import Link from 'next/link';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Card, CardContent } from '@/components/ui/card';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';

type Row = { id: string; primary: string; secondary: string; meta: string; extra?: string; state: string; href?: string; stateTone?: 'success' | 'amber' | 'muted-pill' };
function badgeVariant(row: Row): 'default' | 'secondary' | 'destructive' { return row.stateTone === 'success' ? 'default' : row.state === 'Lost' || row.state === 'Failed' ? 'destructive' : 'secondary'; }
function badgeClass(row: Row) { return row.stateTone === 'amber' ? 'border-amber-300 bg-amber-100 text-amber-900' : row.stateTone === 'success' ? 'bg-emerald-100 text-emerald-800 hover:bg-emerald-100' : row.state === 'Failed' || row.state === 'Lost' ? 'bg-red-100 text-red-800 hover:bg-red-100' : 'bg-slate-100 text-slate-700 hover:bg-slate-100'; }
function displayState(state: string) { return state.replace(/\b\w/g, (letter) => letter.toUpperCase()); }

export function OperationsPage({ eyebrow, title, description, action, columns, rows, emptyCopy }: { eyebrow: string; title: string; description: string; action: string; columns: [string, string, string, string] | [string, string, string, string, string]; rows: Row[]; emptyCopy: string }) {
  const hasExtraColumn = columns.length === 5;
  const statusIndex = hasExtraColumn ? 3 : 2;
  const actionIndex = hasExtraColumn ? 4 : 3;
  return <div className="space-y-5"><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[10px] font-extrabold uppercase tracking-[.15em] text-muted-foreground">{eyebrow}</p><h1 className="mt-1 text-3xl font-bold tracking-tight">{title}</h1><p className="mt-2 text-sm text-muted-foreground">{description}</p></div><Button>{action}</Button></header><Card className="overflow-hidden py-0"><Table className="table-fixed"><TableHeader><TableRow>{columns.map((column, index) => <TableHead key={column} className={index === 0 ? (hasExtraColumn ? 'w-[39%] sm:w-[30%]' : 'w-[46%] sm:w-[40%]') : index === 1 ? 'hidden md:table-cell' : hasExtraColumn && index === 2 ? 'hidden lg:table-cell' : index === statusIndex ? (hasExtraColumn ? 'w-[37%] sm:w-[27%] md:w-[23%]' : 'w-[30%] sm:w-[25%]') : index === actionIndex ? 'w-[24%] text-right sm:w-[20%]' : ''}>{column}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map((row) => <TableRow key={row.id}><TableCell className="whitespace-normal"><p className="font-semibold">{row.primary}</p><p className="mt-1 truncate text-xs text-muted-foreground">{row.secondary}</p></TableCell><TableCell className="hidden text-sm whitespace-normal md:table-cell">{row.meta}</TableCell>{hasExtraColumn && <TableCell className="hidden text-sm whitespace-normal lg:table-cell">{row.extra}</TableCell>}<TableCell><Badge variant={badgeVariant(row)} className={`max-w-full whitespace-normal text-center leading-4 ${badgeClass(row)}`}>{displayState(row.state)}</Badge>{hasExtraColumn && <p className="mt-1 text-xs text-muted-foreground md:hidden">{row.meta}{row.extra ? ` · ${row.extra}` : ''}</p>}</TableCell><TableCell className="text-right">{row.href ? <Button asChild variant="ghost" size="sm" className="px-2"><Link href={row.href}>Review</Link></Button> : <span className="text-muted-foreground">—</span>}</TableCell></TableRow>)}</TableBody></Table>{rows.length === 0 && <CardContent className="py-12 text-center text-sm text-muted-foreground">{emptyCopy}</CardContent>}</Card></div>;
}
