'use client';
import Link from 'next/link';
import { useState } from 'react';
import type { LeadRecord } from '@/lib/operations-repository';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';

export function LeadWorkflow({ lead }: { lead: LeadRecord }) { const [status, setStatus] = useState(lead.status); const [lostReason, setLostReason] = useState(''); const [message, setMessage] = useState(''); const qualify = () => { setStatus('Qualified'); setMessage('Lead qualified in this local demo. Create a pending booking after confirming service and requested time.'); }; const markLost = () => { if (!lostReason.trim()) { setMessage('Add a reason before marking this lead lost.'); return; } setStatus('Lost'); setMessage('Lead marked lost in this local demo.'); }; return <Card><CardHeader><p className="text-[10px] font-extrabold uppercase tracking-[.13em] text-muted-foreground">Lead disposition</p><CardTitle>{status}</CardTitle></CardHeader><CardContent className="space-y-3"><p className="text-sm leading-6 text-muted-foreground">These controls demonstrate frontend mutation states. A backend repository will persist the decision and audit event.</p><Button className="w-full" onClick={qualify} disabled={status === 'Qualified'}>Qualify lead</Button>{status === 'Qualified' && <Button asChild variant="outline" className="w-full"><Link href={`/bookings/new?lead=${lead.id}`}>Create pending booking →</Link></Button>}<label className="grid gap-2 text-xs font-semibold">Lost reason<Input value={lostReason} onChange={(event) => setLostReason(event.target.value)} placeholder="e.g. outside service area"/></label><Button variant="outline" className="w-full" onClick={markLost} disabled={status === 'Lost'}>Mark lost</Button>{message && <p className="rounded-md bg-muted p-3 text-xs text-muted-foreground">{message}</p>}</CardContent></Card>; }
