import Link from 'next/link';
import { formatBookingSchedule } from '@/lib/booking-utils';
import { bookingRepository } from '@/lib/repositories/booking-repository';
import { technicianRepository } from '@/lib/repositories/technician-repository';

const stats = [{ label: 'Calls today', value: '—', trend: 'Available after call integration' }, { label: 'Qualified leads', value: '—', trend: 'Available after lead integration' }, { label: 'Bookings confirmed', value: '—', trend: 'Available after booking status integration' }, { label: 'Active jobs', value: '—', trend: 'Available after jobs integration' }];

export default async function DashboardPage() {
  const [bookings, technicians] = await Promise.all([bookingRepository.list(), technicianRepository.list()]);
  const needsAssignment = bookings.filter((booking) => !booking.technicianId).length;
  return <><header className="page-header"><div><p className="eyebrow">Operations overview</p><h1>Good morning, Aisha</h1></div><Link className="button primary" href="/bookings">Review bookings</Link></header><section className="shift-tape" aria-label="Upcoming booking schedule"><div className="tape-head"><h2>Upcoming bookings</h2><span className="live">● {bookings.length} booking{bookings.length === 1 ? '' : 's'} scheduled</span></div><div className="tape-items">{bookings.map((booking, index) => <div className="tape-item" key={booking.id}><span className={index === 0 ? 'pin' : undefined}/>{formatBookingSchedule(booking)} · {booking.service}</div>)}</div></section><section className="stats" aria-label="Today’s key metrics">{stats.map((stat) => <article className="stat-card" key={stat.label}><p>{stat.label}</p><strong>{stat.value}</strong><span>{stat.trend}</span><div className="spark"/></article>)}</section><section className="overview-grid"><article className="panel"><div className="panel-header"><h2>Bookings needing attention</h2><Link href="/bookings">View all →</Link></div><div className="attention-list">{bookings.filter((booking) => !booking.technicianId).map((booking) => <Link href={`/bookings/${booking.id}`} className="attention-row" key={booking.id}><div><strong>{booking.service}</strong><span>{booking.customer} · {formatBookingSchedule(booking)}</span></div><span className="pill amber">Assign technician</span></Link>)}</div></article><article className="panel"><div className="panel-header"><h2>Technician availability</h2><Link href="/technicians">View team →</Link></div>{technicians.map((tech) => <div className="technician-row" key={tech.id}><span className="initials">{tech.initials}</span><div><strong>{tech.name}</strong><span>{tech.trade}</span></div><span className={`pill ${tech.availability === 'Available' ? 'success' : 'muted-pill'}`}>{tech.availability}</span></div>)}</article><aside className="panel verification"><span className="alert-mark">!</span><div><h2>{needsAssignment} booking{needsAssignment === 1 ? '' : 's'} need assignment</h2><p>Review the customer, service, and availability before sharing details with a technician.</p></div><Link className="button" href="/bookings">Open bookings</Link></aside></section></>;
}
