import Link from 'next/link';
import { initialBookings, technicians } from '@/lib/mock-data';

const stats = [{ label: 'Calls today', value: '312', trend: '18% vs. yesterday' }, { label: 'Qualified leads', value: '76', trend: '24% vs. yesterday' }, { label: 'Bookings confirmed', value: '28', trend: '27% vs. yesterday' }, { label: 'Active jobs', value: '42', trend: '12% vs. yesterday' }];

export default function DashboardPage() {
  const needsAssignment = initialBookings.filter((booking) => !booking.technicianId).length;
  return <><header className="page-header"><div><p className="eyebrow">Operations overview · Tuesday, 20 May</p><h1>Good morning, Aisha</h1></div><Link className="button primary" href="/bookings">Review bookings</Link></header><section className="shift-tape" aria-label="Today's job schedule"><div className="tape-head"><h2>Today’s shift tape</h2><span className="live">● Live schedule · 5 jobs in motion</span></div><div className="tape-items">{['08:00 · Kitchen remodel · Carlos on site', '10:00 · Water heater install · Mike en route', '12:30 · HVAC maintenance · Aisha booked', '14:00 · Electrical upgrade · Jordan follow-up', '16:00 · Drain cleaning · Carlos booked'].map((item, index) => <div className="tape-item" key={item}><span className={index === 0 ? 'pin' : undefined}/>{item}</div>)}</div></section><section className="stats" aria-label="Today’s key metrics">{stats.map((stat) => <article className="stat-card" key={stat.label}><p>{stat.label}</p><strong>{stat.value}</strong><span>↑ {stat.trend}</span><div className="spark"/></article>)}</section><section className="overview-grid"><article className="panel"><div className="panel-header"><h2>Bookings needing attention</h2><Link href="/bookings">View all →</Link></div><div className="attention-list">{initialBookings.filter((booking) => !booking.technicianId).map((booking) => <Link href={`/bookings/${booking.id}`} className="attention-row" key={booking.id}><div><strong>{booking.service}</strong><span>{booking.customer} · {booking.date}</span></div><span className="pill amber">Assign technician</span></Link>)}</div></article><article className="panel"><div className="panel-header"><h2>Technician availability</h2><Link href="/technicians">View team →</Link></div>{technicians.map((tech) => <div className="technician-row" key={tech.id}><span className="initials">{tech.initials}</span><div><strong>{tech.name}</strong><span>{tech.trade}</span></div><span className={`pill ${tech.availability === 'Available' ? 'success' : 'muted-pill'}`}>{tech.availability}</span></div>)}</article><aside className="panel verification"><span className="alert-mark">!</span><div><h2>{needsAssignment} booking{needsAssignment === 1 ? '' : 's'} need assignment</h2><p>Review the customer, service, and availability before sharing details with a technician.</p></div><Link className="button" href="/bookings">Open bookings</Link></aside></section></>;
}
